title: OpenGenomeBrowser
description: The solution for organizing and analysing your microbes.
remote_theme: pages-themes/slate@v0.2.0

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART"]
