theme: jekyll-theme-slate
title: OpenGenomeBrowser
description: OpenGenomeBrowser is a dynamic and scalable web platform for comparative genomics.

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART"]

# Note to self: Check if all links work using `linkchecker https://opengenomebrowser.github.io/`