theme: jekyll-theme-slate
title: OpenGenomeBrowser
description: The solution for organizing and analysing your microbes.

markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE", "SMART"]

# Note to self: Check if all links work using `linkchecker https://opengenomebrowser.github.io/`